// Base
JSON.stringify(Game.rooms["sim"].lookForAtArea(LOOK_STRUCTURES, 1, 1, 7, 7, true));
[{
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 2,
    "y": 1
}, {
    "type": "structure",
    "structure": {
        "structureType": "tower"
    },
    "x": 4,
    "y": 1
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 6,
    "y": 1
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 1,
    "y": 2
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 4,
    "y": 2
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 5,
    "y": 2
}, {
    "type": "structure",
    "structure": {
        "structureType": "link"
    },
    "x": 6,
    "y": 2
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 7,
    "y": 2
}, {
    "type": "structure",
    "structure": {
        "structureType": "storage"
    },
    "x": 3,
    "y": 3
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 4,
    "y": 3
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 6,
    "y": 3
}, {
    "type": "structure",
    "structure": {
        "structureType": "tower"
    },
    "x": 1,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "spawn"
    },
    "x": 2,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 3,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "container"
    },
    "x": 4,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 5,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "powerSpawn"
    },
    "x": 6,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "tower"
    },
    "x": 7,
    "y": 4
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 2,
    "y": 5
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 4,
    "y": 5
}, {
    "type": "structure",
    "structure": {
        "structureType": "terminal"
    },
    "x": 5,
    "y": 5
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 1,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 3,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "lab"
    },
    "x": 4,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 7,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 2,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "tower"
    },
    "x": 4,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 6,
    "y": 7
}];
// Outpost
JSON.stringify(Game.rooms["sim"].lookForAtArea(LOOK_STRUCTURES, 6, 16, 14, 24, true));
[{
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 17,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 18,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 19,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 20,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 21,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 22,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 23,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 6
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 17,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 18,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 19,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 20,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 21,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 22,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 23,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 7
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 16,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 17,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 18,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 19,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 20,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 21,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 22,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 23,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 24,
    "y": 8
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 17,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 18,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 19,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 20,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 21,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 22,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 23,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 9
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 17,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 18,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 19,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "tower"
    },
    "x": 20,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 21,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 22,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 23,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 10
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 17,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 18,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "link"
    },
    "x": 19,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 20,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "spawn"
    },
    "x": 21,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 22,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 23,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 11
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 16,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 17,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 18,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 19,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 20,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 21,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 22,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 23,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 24,
    "y": 12
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 17,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 17,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 18,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 18,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 19,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 19,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 20,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 20,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 21,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 21,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "extension"
    },
    "x": 22,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 22,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 23,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "rampart"
    },
    "x": 23,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 13
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 16,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 17,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 18,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 19,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 20,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 21,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "road"
    },
    "x": 22,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 23,
    "y": 14
}, {
    "type": "structure",
    "structure": {
        "structureType": "constructedWall"
    },
    "x": 24,
    "y": 14
}]